cmake_minimum_required(VERSION 3.16.0)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR komdiv)

set(TOOLCHAIN_PREFIX bt23h)
set(TOOLCHAIN_BIN_DIR /usr/baget-tools/H-linux86/bin)

set(CMAKE_C_COMPILER ${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_LINKER     ${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_PREFIX}-ld)
set(CMAKE_OBJDUMP    ${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_PREFIX}-objdump)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
