set(CMAKE_C_COMPILE_OBJECT
    # "<CMAKE_C_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <SOURCE>.i -E <SOURCE>"
    "<CMAKE_C_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT>.i -E <SOURCE>"
    "<CMAKE_C_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE>"
)

set(CMAKE_CXX_COMPILE_OBJECT
    # "<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <SOURCE>.ii -E <SOURCE>"
    "<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT>.ii -E <SOURCE>"
    "<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE>"
)
