#ifndef _SYS_OBJCLASSES_H
#define _SYS_OBJCLASSES_H

/* Зарегистрированные системные типы объектов */
enum obj_classes {
  CLASS_SYSCONTROL = 1,
  CLASS_MEMCONTROL,
  CLASS_SEMCONTROL,
  CLASS_SEMCONTROLPX,
  CLASS_EVNCONTROL,        /*05*/
  CLASS_MQPCONTROL,
  CLASS_MQPCONTROLPX,
  CLASS_IODEVCONTROL,
  CLASS_HSHCONTROL,
  CLASS_QUECONTROL,        /*10*/
  CLASS_MTXCONTROLPX,
  CLASS_CNDCONTROLPX,
  CLASS_THREADCONTROL,
  CLASS_TMRCONTROLPX,
  CLASS_CLCCONTROLPX,      /*15*/
  CLASS_SYMCONTROL,
  CLASS_STDIOCONTROL,
  CLASS_ECBCONTROL,
  CLASS_SELCONTROL,
  CLASS_PIPECONTROL,       /*20*/
  CLASS_FILECONTROL,
  CLASS_MODULECONTROL,
  CLASS_MEMCONTROLMP,
  CLASS_SEMCONTROLMP,
  CLASS_SEMCONTROLPXMP,    /*25*/
  CLASS_MQPCONTROLMP,
  CLASS_MQPCONTROLPXMP,
  CLASS_THREADCONTROLMP,
  CLASS_QPORTCONTROL,
  CLASS_SPORTCONTROL,      /*30*/
  CLASS_IOFILECONTROL,
  CLASS_QLISTCONTROL,
  CLASS_QSAPCONTROL,
  CLASS_MPCONTROL
};

#define CLASS_TOTAL   CLASS_MPCONTROL+2
#define CLASS_ANY     CLASS_TOTAL

#endif /* _SYS_OBJCLASSES_H */

